### ISSUE TITLE
Build for Python 3.6

### ISSUE THREAD

**Issue by koverholt** [conda/kapsel#29]
The latest version of Anaconda 4.3 includes Python 3.6. The latest versions of `conda-kapsel` are built for py27, py34, and py35.

Could we push a version of `conda-kapsel` built for Python 3.6 as well?

**Comment by havocp** [comment]
#32 is the PR in progress, some missing dependencies right now. Could hack the deps out, or go get them built.

**Comment by havocp** [comment]
0.4.0 has 3.6 packages.
